# Author: Juan David Amezquita Nuñez

Taller 01: Numpy

In [2]:
import numpy as np

In [3]:
#1. Crear un arreglo de 5 elementos enteros, todos iguales a 10.
array = np.full(5,10)
print(array)

[10 10 10 10 10]


In [4]:
# 2. Crear una matriz 2x3 con todos los elementos iguales a 5.
matrix = np.full((2, 3), 5)
print(matrix)

[[5 5 5]
 [5 5 5]]


In [8]:
# 3. Crear un arreglo multidimensional aleatorio de 3 tensores, cada uno de 2 filas y 3 columna.
arraytup = np.random.randint(1, 10, (3, 2, 3))
print(arraytup)

[[[6 5 7]
  [5 4 6]]

 [[4 7 1]
  [6 8 9]]

 [[6 7 9]
  [9 5 7]]]


In [11]:
# 4. Dados los siguientes arreglos:
arr1 = np.array([1, 2, 3, 4, 5]) 
arr2 = np.array([6, 7, 8, 9, 10])
#Sumar, restar y multiplicar.
sum = arr1 + arr2
res = arr1 - arr2
mult = arr1 * arr2
print("Suma: ", sum)
print("Resta: ", res)
print("Multiplicacion: ", mult)

Suma:  [ 7  9 11 13 15]
Resta:  [-5 -5 -5 -5 -5]
Multiplicacion:  [ 6 14 24 36 50]


In [12]:
# 5. Dado el siguiente arreglo:
data = np.array([23, 17, 25, 30, 21, 29, 18])
#Calcular la media y la desviación estándar.
media = np.mean(data)
desviacion = np.std(data)
print(media)
print(desviacion)

23.285714285714285
4.681705602335411


In [13]:
# 6. Dado el siguiente arreglo:
datos = np.array([12, 15, 8, 10, 5, 14, 9, 7])
# Crear un nuevo arreglo que contenga los elementos mayores o iguales a 10.
condicion = datos >= 10
nuevo = datos[condicion]
print(nuevo)

[12 15 10 14]


In [14]:
# 7. Dado el siguiente arreglo: 
data = np.array([[12, 15, 20, 25], [8, 10, 12, 14], [18, 20, 22, 24]])

# 7.1 Mostrar el numero por pantalla el numero 24.
print("7.1: ", data[2,3])
# 7.2 Mostrar la fila 3: [18,20,22,24].
print("7.2: ", data[2,:])
# 7.3 Mostrar la columna 2: [15,10,20].
print("7.3: ", data[:,1])

7.1:  24
7.2:  [18 20 22 24]
7.3:  [15 10 20]


In [15]:
# 8. Dado el siguiente arreglo multidimensional:
arregloMultiD = np.random.rand(4,8,4)

# 8.1 Volverlo de manera lineal.
lineal = arregloMultiD.ravel()
print("8.1: ", lineal.shape)
# 8.2 Reajustarlo en tuplas:
tuplas = lineal.reshape(-1,2) # -1 significa que NumPy infiere el número de filas
print("8.2: ", tuplas.shape)

8.1:  (128,)
8.2:  (64, 2)
